import doctest = doctest%lib{doctest}

./: exe{all_features}: {hxx cxx}{* -assert_returns_disabled*} $doctest testscript

cxx.poptions =+ "-I$src_base"

# Easy way to fix test coverage - disable colors and crash handling
#
cxx.poptions += \
  -DDOCTEST_CONFIG_COLORS_NONE \
  -DDOCTEST_CONFIG_NO_POSIX_SIGNALS \
  -DDOCTEST_CONFIG_NO_WINDOWS_SEH

if ($cxx.target.system != 'win32-msvc')
  cxx.libs += -pthread

./: test_output/file{*.txt}
